#!/usr/bin/env bash

git config --global alias.graphall "log --graph --oneline --decorate --tags --all"
git config --global alias.ga "log --graph --oneline --decorate --tags --all"
git config --global alias.graphhead "log --graph --oneline --decorate --tags HEAD"
git config --global alias.gh "log --graph --oneline --decorate --tags HEAD"
